describe("test runner", function()
	local n
	before_each(function() n = 1 end)
	it("compares values", function()
		assert_eq(n + 1, 2)
		assert_same({ a = { 1, 2 } }, { a = { 1, 2 } })
		assert_true(true)
		assert_false(nil)
		assert_near(0.1 + 0.2, 0.3, 1e-9)
	end)
	it("detects errors", function()
		assert_error(function() error("boom") end, "boom")
	end)
	it("decodes json with the vendored library", function()
		local json = require("tools.lib.json")
		assert_same(json.decode('{"a":[1,2,3]}'), { a = { 1, 2, 3 } })
	end)
end)
