local views = require("client.views")
local levels = require("client.levels")
local config = require("meta.config")
local iap = require("client.services.iap")
local H = require("tests.meta.helper")

local T = H.T0

-- a level file reader over a table {[n] = level table}
local function fake_levels(files)
	local json = require("tools.lib.json")
	levels._reset()
	levels.read = function(path)
		local n = tonumber(string.match(path, "level_(%d+)%.json$"))
		local f = n and files[n]
		if type(f) == "string" then return f end
		return f and json.encode(f) or nil
	end
	levels.decode = json.decode
end

describe("client.views (meta screens)", function()
	before_each(function() levels._reset() end)

	it("shows the level button with its difficulty tag and streak notes", function()
		fake_levels({ [1] = { difficulty = "hard", goals = {} } })
		local m = H.new()
		local v = views.level_button(m, levels)
		assert_eq(v.level, 1)
		assert_eq(v.tag, "town.hard")
		assert_eq(#v.notes, 3)
		assert_false(v.notes[1].lit)
		assert_false(v.all_done)
	end)

	it("has no tag for easy levels or a missing file", function()
		fake_levels({ [1] = { difficulty = "easy" } })
		local m = H.new()
		assert_eq(views.level_button(m, levels).tag, nil)
		levels._reset()
		fake_levels({})
		assert_eq(views.level_button(m, levels).tag, nil)
		assert_eq(views.level_button(m, levels).level, 1)
	end)

	it("lights the streak notes after wins from level 12", function()
		fake_levels({})
		local m = H.new()
		H.advance_to(m, 12, T)
		H.win(m, T)
		H.win(m, T)
		local v = views.level_button(m, levels)
		assert_true(v.notes[1].lit and v.notes[2].lit)
		assert_false(v.notes[3].lit)
		assert_eq(v.streak, 2)
	end)

	it("builds the start window: goals, moves, boosters, what a loss costs", function()
		fake_levels({ [1] = { difficulty = "super_hard", moves = 20,
			goals = { { type = "collect", color = "red", count = 30 }, { type = "break", item = "record_box", count = 9 } } } })
		local m = H.new()
		local info = levels.load(1)
		local v = views.start(m, 1, info, T, levels, config.levels.free_up_to)
		assert_eq(v.tag, "town.super_hard")
		assert_eq(#v.goals, 2)
		assert_eq(v.goals[1].image, "pieces/red")
		assert_eq(v.goals[2].image, "blockers/record_box_1")
		assert_eq(v.moves, 20)
		assert_eq(#v.boosters, 3)
		assert_eq(v.boosters[1].id, "riff")
		assert_false(v.boosters[1].unlocked)
		assert_false(v.life_cost) -- level 1 is free
		assert_true(v.can_start)
	end)

	it("says a loss costs a life after the free levels, not with unlimited lives", function()
		fake_levels({})
		local m = H.new()
		H.advance_to(m, config.levels.free_up_to + 1, T)
		local n = m:level_to_play()
		local later = T + 3 * 3600 -- the unlimited lives of the level 20 chest are over
		local v = views.start(m, n, nil, later, levels, config.levels.free_up_to)
		assert_true(v.life_cost)
		assert_false(v.infinite)
		assert_same(v.goals, {})
		m:grant({ infinite_minutes = 30 }, "test", later)
		assert_false(views.start(m, n, nil, later, levels, config.levels.free_up_to).life_cost)
	end)

	it("marks streak boosters free and not selectable (they are placed anyway)", function()
		fake_levels({})
		local m = H.new()
		H.advance_to(m, 13, T)
		H.win(m, T) -- streak 1 from level 12 on: a free riff at the next start
		local slots = views.start_boosters(m, m:level_to_play())
		assert_true(slots[1].unlocked)
		assert_true(slots[1].free)
		assert_false(slots[1].selectable)
		assert_same(views.picked(slots, { riff = true }), {})
	end)

	it("lists the store products in display order with their contents", function()
		local list = views.shop_products(iap.PRODUCTS, false)
		assert_eq(#list, 5)
		assert_eq(list[1].id, "starter_pack")
		assert_true(list[1].best)
		assert_eq(list[1].coins, 1000)
		assert_eq(list[1].infinite_minutes, 60)
		assert_eq(#list[1].boosters, 3)
		assert_false(list[2].available)
		assert_true(views.shop_products(iap.PRODUCTS, true)[2].available)
	end)

	it("lists what a chest holds, same boosters counted together", function()
		local items = views.chest_items({ coins = 60, boosters = { "stick", "riff", "stick" }, infinite_minutes = 15 })
		assert_eq(#items, 4)
		assert_eq(items[1].kind, "coins")
		assert_eq(items[1].amount, 60)
		assert_eq(items[2].id, "stick")
		assert_eq(items[2].amount, 2)
		assert_eq(items[3].id, "riff")
		assert_eq(items[4].kind, "infinite")
		assert_same(views.chest_items(nil), {})
		assert_eq(#views.chest_items({ coins = 0, boosters = {} }), 0)
	end)

	it("describes an unlock gift with its size from the config", function()
		local g = views.gift("riff", config)
		assert_eq(g.count, 3)
		assert_eq(g.icon, "specials/riff")
		assert_eq(views.gift("nope", config).count, 0)
	end)

	it("lists the jukebox songs: current with its layers, the rest locked", function()
		local m = H.new()
		local by_id = {}
		for _, d in ipairs(H.districts().districts) do by_id[d.id] = d end
		local rows = views.jukebox(m, by_id)
		assert_eq(rows[1].state, "current")
		assert_false(rows[1].playable) -- nothing built yet
		assert_eq(rows[2].state, "locked")
		assert_eq(rows[1].bpm, 90)
		H.win(m, T)
		local t = m:next_task()
		assert_true(m:complete_task(t.district, t.id))
		rows = views.jukebox(m, by_id)
		assert_true(rows[1].playable)
		assert_eq(rows[1].stems, 1)
	end)

	it("reads the refill offer and the settings from the meta", function()
		local m = H.new()
		local r = views.refill(m, T)
		assert_false(r.available)
		assert_eq(r.reason, "full")
		local s = views.settings(m)
		assert_eq(s.input_mode, "swipe")
		assert_eq(s.language, "auto")
		assert_eq(#s.languages, 3)
	end)
end)
