local inventory = require("meta.inventory")
local H = require("tests.meta.helper")

local T = H.T0

describe("booster rules", function()
	it("unlock by level", function()
		assert_same(inventory.newly_unlocked(0, 1), {})
		assert_same(inventory.newly_unlocked(7, 8), { "stick" })
		assert_same(inventory.newly_unlocked(8, 9), {})
		assert_same(inventory.newly_unlocked(11, 12), { "riff" })
		assert_same(inventory.newly_unlocked(0, 101),
			{ "stick", "row_light", "col_light", "remix", "riff", "sub", "disco" })
		assert_false(inventory.is_unlocked("disco", 21))
		assert_true(inventory.is_unlocked("disco", 22))
	end)

	it("give streak boosters only from level 12 and only unlocked ones", function()
		assert_same(inventory.streak_boosters(5, 11), {})
		assert_same(inventory.streak_boosters(0, 30), {})
		assert_same(inventory.streak_boosters(1, 12), { "riff" })
		assert_same(inventory.streak_boosters(2, 15), { "riff" }, "sub unlocks at 16")
		assert_same(inventory.streak_boosters(2, 16), { "riff", "sub" })
		assert_same(inventory.streak_boosters(3, 20), { "riff", "sub" }, "disco unlocks at 22")
		assert_same(inventory.streak_boosters(3, 22), { "riff", "sub", "disco" })
		assert_same(inventory.streak_boosters(9, 60), { "riff", "sub", "disco" })
	end)

	it("sort ids into catalogue order", function()
		assert_same(inventory.sort({ "disco", "riff", "stick", "riff" }), { "stick", "riff", "riff", "disco" })
	end)

	it("reject unknown ids and the wrong kind", function()
		assert_error(function() inventory.need("hammer") end, "unknown booster")
		assert_error(function() inventory.need("stick", "pre") end, "not a pre-level booster")
	end)
end)

describe("boosters in the meta", function()
	it("give the unlock gift when the level is reached", function()
		local m = H.new()
		local gifts = { [8] = { "stick", 3 }, [12] = { "riff", 3 }, [14] = { "row_light", 2 }, [16] = { "sub", 3 },
			[18] = { "col_light", 2 }, [22] = { "disco", 3 }, [25] = { "remix", 2 } }
		for level = 2, 25 do
			local r = H.win(m, T)
			local g = gifts[level]
			if g then
				assert_same(r.unlocked, { g[1] }, "level " .. level)
				assert_eq(H.ledger_sum(m:drain_ledger(), g[1], "unlock_gift"), g[2], g[1])
			else
				assert_same(r.unlocked, {}, "level " .. level)
				m:drain_ledger()
			end
		end
	end)

	it("show the inventory with lock state", function()
		local m = H.new()
		H.advance_to(m, 14)
		local inv = m:inventory()
		assert_eq(#inv, 7)
		assert_same(inv[1], { id = "stick", kind = "in", count = 4, unlocked = true, unlock_level = 8, pack_price = 450, pack_size = 3 },
			"3 gift + 1 from the chest of level 10")
		assert_eq(inv[2].id, "row_light")
		assert_true(inv[2].unlocked)
		assert_eq(inv[3].id, "col_light")
		assert_false(inv[3].unlocked)
		assert_eq(m:booster_count("riff"), 3)
	end)

	it("sell packs of 3 for coins", function()
		local prices = { stick = 450, row_light = 600, col_light = 600, remix = 450, riff = 600, sub = 750, disco = 900 }
		local m = H.new()
		H.advance_to(m, 25)
		H.give(m, "coins", 10000)
		for id, price in pairs(prices) do -- order-free: independent checks
			local coins, count = m:coins(), m:booster_count(id)
			assert_same(m:buy_booster_pack(id), { id = id, count = 3, price = price })
			assert_eq(m:coins(), coins - price, id)
			assert_eq(m:booster_count(id), count + 3, id)
		end
	end)

	it("refuse packs of locked boosters and packs without coins", function()
		local m = H.new()
		local ok, why = m:buy_booster_pack("stick")
		assert_false(ok)
		assert_eq(why, "locked")
		H.advance_to(m, 8)
		H.give(m, "coins", -m:coins() + 449)
		m:drain_ledger()
		ok, why = m:buy_booster_pack("stick")
		assert_false(ok)
		assert_eq(why, "not_enough_coins")
		assert_eq(m:coins(), 449)
		assert_eq(m:booster_count("stick"), 3)
		assert_same(m:drain_ledger(), {})
	end)

	it("spend in-level boosters during an attempt", function()
		local m = H.new()
		H.advance_to(m, 8)
		local ok, why = m:use_booster("stick")
		assert_false(ok)
		assert_eq(why, "no_run")
		assert_true(m:start_level({ id = 8, difficulty = "easy" }, nil, T))
		m:drain_ledger()
		assert_true(m:use_booster("stick"))
		assert_eq(m:booster_count("stick"), 2)
		assert_same(m:drain_ledger(), { { item = "stick", delta = -1, balance = 2, reason = "in_level_booster", flow = "sink" } })
		ok, why = m:use_booster("row_light")
		assert_false(ok)
		assert_eq(why, "locked")
		assert_true(m:use_booster("stick"))
		assert_true(m:use_booster("stick"))
		ok, why = m:use_booster("stick")
		assert_false(ok)
		assert_eq(why, "not_enough_stick")
		assert_error(function() m:use_booster("riff") end, "not an in-level booster")
		assert_true(m:run().moved, "a booster counts as the first action")
	end)

	it("spend chosen pre-level boosters at the start", function()
		local m = H.new()
		H.advance_to(m, 22)
		m:drain_ledger()
		assert_eq(m:booster_count("riff"), 4, "3 gift + 1 from the chest of level 20")
		local r = m:start_level({ id = 22, difficulty = "easy" }, { "disco", "riff" }, T)
		assert_same(r.paid_boosters, { "riff", "disco" })
		assert_same(r.streak_boosters, { "riff", "sub", "disco" }, "10 wins in a row")
		assert_same(r.boosters, { "riff", "sub", "disco", "riff", "disco" }, "streak ones first")
		assert_eq(m:booster_count("riff"), 3)
		assert_eq(m:booster_count("sub"), 3, "streak boosters are free")
		assert_eq(m:booster_count("disco"), 2)
		local ledger = m:drain_ledger()
		assert_eq(H.ledger_sum(ledger, "riff", "pre_booster"), -1)
		assert_eq(H.ledger_sum(ledger, "disco", "pre_booster"), -1)
	end)

	it("refuse locked or missing pre-level boosters without spending anything", function()
		local m = H.new()
		H.advance_to(m, 16)
		local ok, why = m:start_level({ id = 16, difficulty = "easy" }, { "riff", "disco" }, T)
		assert_false(ok)
		assert_eq(why, "locked")
		assert_eq(m:booster_count("riff"), 3)
		H.give(m, "sub", -3)
		ok, why = m:start_level({ id = 16, difficulty = "easy" }, { "riff", "sub" }, T)
		assert_false(ok)
		assert_eq(why, "not_enough_sub")
		assert_eq(m:booster_count("riff"), 3)
		assert_eq(m:run(), nil)
		assert_error(function() m:start_level({ id = 16, difficulty = "easy" }, { "riff", "riff" }, T) end, "twice")
		assert_error(function() m:start_level({ id = 16, difficulty = "easy" }, { "stick" }, T) end, "pre-level")
	end)

	it("return paid pre-level boosters when the level is left before the first move", function()
		local m = H.new()
		H.advance_to(m, 16)
		assert_true(m:start_level({ id = 16, difficulty = "easy" }, { "riff", "sub" }, T))
		assert_eq(m:booster_count("riff"), 2)
		m:drain_ledger()
		assert_true(m:cancel_level())
		assert_eq(m:booster_count("riff"), 3)
		assert_eq(m:booster_count("sub"), 3)
		local ledger = m:drain_ledger()
		assert_eq(H.ledger_sum(ledger, "riff", "cancel_refund"), 1)
		assert_eq(H.ledger_sum(ledger, "sub", "cancel_refund"), 1)
	end)
end)
