local Meta = require("meta.meta")
local H = require("tests.meta.helper")

local T = H.T0
-- levels 10 and 20 give 45 minutes of infinite lives; lives are tested after that
local P = T + 10000

describe("level progression", function()
	it("plays levels strictly in order", function()
		local m = H.new()
		assert_eq(m:level_to_play(), 1)
		assert_false(m:all_done())
		local ok, why = m:can_start(2, T)
		assert_false(ok)
		assert_eq(why, "not_next_level")
		assert_true(m:can_start(1, T))
		assert_true(m:start_level({ id = 1, difficulty = "easy" }, nil, T))
		ok, why = m:can_start(1, T)
		assert_false(ok)
		assert_eq(why, "run_active")
		local r = m:finish_level({ won = true, level_id = 1, moves_at_win = 2 }, T)
		assert_eq(r.next_level, 2)
		assert_eq(m:level_to_play(), 2)
	end)

	it("ends in the all_done state after level 100", function()
		local m = H.new()
		H.advance_to(m, 100)
		local r = H.win(m, T)
		assert_eq(r.next_level, nil)
		assert_true(m:all_done())
		assert_eq(m:level_to_play(), nil)
		local ok, why = m:can_start(101, T)
		assert_false(ok)
		assert_eq(why, "all_done")
		assert_same(m:streak_boosters_for_next_start(), {})
		assert_true(m:inventory()[4].unlocked, "everything stays unlocked")
	end)

	it("counts attempts and consecutive fails for the assist", function()
		local m = H.new()
		H.advance_to(m, 3)
		for i = 1, 5 do
			local r = m:start_level({ id = 3, difficulty = "easy" }, nil, T)
			assert_eq(r.attempt, i)
			assert_eq(r.assist, i - 1)
			m:note_move()
			local l = m:finish_level({ won = false, level_id = 3 }, T)
			assert_eq(l.fails, i)
		end
		assert_same(m:attempts(3), { attempts = 5, fails = 5 })
		local r = m:start_level({ id = 3, difficulty = "easy" }, nil, T)
		assert_eq(r.attempt, 6)
		assert_eq(r.assist, 5)
		m:finish_level({ won = true, level_id = 3, moves_at_win = 0 }, T)
		assert_same(m:attempts(3), { attempts = 6, fails = 0 })
		assert_same(m:attempts(50), { attempts = 0, fails = 0 })
	end)

	it("does not count an attempt left before the first move", function()
		local m = H.new()
		local r = m:start_level({ id = 1, difficulty = "easy" }, nil, T)
		assert_eq(r.attempt, 1)
		assert_true(m:cancel_level())
		assert_eq(m:run(), nil)
		assert_same(m:attempts(1), { attempts = 0, fails = 0 })
		r = m:start_level({ id = 1, difficulty = "easy" }, nil, T)
		assert_eq(r.attempt, 1, "same attempt number, same board")
		m:note_move()
		local ok, why = m:cancel_level()
		assert_false(ok)
		assert_eq(why, "moved")
	end)

	it("reports the salt with every start", function()
		local m = H.new(777)
		assert_eq(m:start_level({ id = 1, difficulty = "easy" }, nil, T).salt, 778)
	end)

	it("pays the win and counts stats", function()
		local m = H.new()
		H.advance_to(m, 21)
		local coins, stars = m:coins(), m:stars()
		assert_true(m:start_level({ id = 21, difficulty = "super_hard" }, nil, T))
		local r = m:finish_level({ won = true, level_id = 21, difficulty = "super_hard", moves_at_win = 4 }, T)
		assert_eq(r.coins, 75 + 20)
		assert_eq(r.stars, 3)
		assert_eq(m:coins(), coins + 95)
		assert_eq(m:stars(), stars + 3)
		assert_eq(m:stats().wins, 21)
		H.lose(m, P)
		assert_eq(m:stats().losses, 1)
	end)

	it("rejects results that do not match the attempt", function()
		local m = H.new()
		local ok, why = m:finish_level({ won = true, level_id = 1, moves_at_win = 0 }, T)
		assert_false(ok)
		assert_eq(why, "no_run")
		m:start_level({ id = 1, difficulty = "easy" }, nil, T)
		assert_error(function() m:finish_level({ won = true, level_id = 2, moves_at_win = 0 }, T) end, "running level")
		assert_error(function() m:finish_level({ won = true, level_id = 1, difficulty = "hard", moves_at_win = 0 }, T) end, "difficulty")
		assert_error(function() m:finish_level({ won = true, level_id = 1 }, T) end, "moves_at_win")
		assert_true(m:run() ~= nil, "a rejected result leaves the attempt open")
		assert_error(function() m:start_level({ id = 1, difficulty = "insane" }, nil, T) end, "difficulty")
		assert_error(function() m:can_start("1", T) end, "integer")
		assert_error(function() m:can_start(1) end, "now")
		assert_error(function() m:attempts("1") end, "integer")
	end)

	it("accepts only a boolean won and quit_after_first_move", function()
		local m = H.new()
		m:start_level({ id = 1, difficulty = "easy" }, nil, T)
		m:note_move()
		assert_error(function() m:finish_level({ won = 0, level_id = 1, moves_at_win = 0 }, T) end, "won must be true or false")
		assert_error(function() m:finish_level({ won = "false", level_id = 1 }, T) end, "won must be true or false")
		assert_error(function() m:finish_level({ level_id = 1 }, T) end, "won must be true or false")
		assert_error(function() m:finish_level({ won = false, level_id = 1, quit_after_first_move = 1 }, T) end,
			"quit_after_first_move must be nil or a boolean")
		assert_error(function() m:finish_level({ won = true, level_id = 1, moves_at_win = 0, quit_after_first_move = true }, T) end,
			"contradicts")
		assert_error(function() m:finish_level(nil, T) end, "result table")
		assert_eq(m:coins(), 500, "nothing was paid")
		assert_true(m:run() ~= nil)
		assert_true(m:finish_level({ won = true, level_id = 1, moves_at_win = 0, quit_after_first_move = false }, T).won)
	end)

	it("refuses a loss before the first move", function()
		local m = H.new()
		H.advance_to(m, 21)
		m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		assert_error(function() m:finish_level({ won = false, level_id = 21 }, P) end, "a loss needs a move")
		assert_error(function() m:finish_level({ won = false, level_id = 21, quit_after_first_move = false }, P) end,
			"cancel_level()")
		assert_eq(m:lives(P).count, 5)
		assert_same(m:attempts(21), { attempts = 0, fails = 0 })
		assert_true(m:cancel_level(), "the attempt is still open and can be left")
	end)

	it("counts quit_after_first_move = true as the move", function()
		local m = H.new()
		H.advance_to(m, 21)
		m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		local r = m:finish_level({ won = false, level_id = 21, quit_after_first_move = true }, P)
		assert_eq(r.reason, "quit")
		assert_true(r.life_lost)
	end)
end)

describe("progress restore", function()
	local progress = require("meta.progress")

	it("accepts level records only under their canonical key", function()
		local p = progress.restore({ levels = {
			["3"] = { attempts = 1, fails = 1 }, ["03"] = { attempts = 9, fails = 9 }, ["3.0"] = { attempts = 8 },
			[" 3"] = { attempts = 7 }, ["0x3"] = { attempts = 6 }, ["4"] = { attempts = 2, fails = 0 },
			["0"] = { attempts = 5 }, ["-1"] = { attempts = 5 }, ["2.5"] = { attempts = 5 }, x = { attempts = 5 },
		} })
		assert_same(p.levels, { ["3"] = { attempts = 1, fails = 1 }, ["4"] = { attempts = 2, fails = 0 } })
		assert_true(progress.is_level_key("100"))
		assert_false(progress.is_level_key(3))
	end)

	it("keeps an open attempt only for the next level, free up to level 20, boosters once", function()
		local p = progress.restore({ beaten = 14, run = { level_id = 15, difficulty = "hard", free = false,
			boosters = { "riff", "riff", "stick", "hammer", "sub" } } })
		assert_true(p.run.free, "levels 1..20 never cost a life")
		assert_same(p.run.boosters, { "riff", "sub" })
		p = progress.restore({ beaten = 14, run = { level_id = 16, difficulty = "hard" } })
		assert_eq(p.run, nil)
		p = progress.restore({ beaten = 14, run = { level_id = 15, difficulty = "insane" } })
		assert_eq(p.run, nil)
	end)

	it("keeps progress past the last level from a build with more levels", function()
		local m = H.new()
		H.advance_to(m, 25)
		local t = H.json_round_trip(m:serialize())
		t.progress.beaten = 120
		t.progress.run = { level_id = 121, difficulty = "hard", attempt = 1, moved = true }
		t.checksum = require("meta.save").checksum(t)
		local m2, info = Meta.load(H.districts(), t, nil, 1, P)
		assert_eq(info.interrupted, "loss", "the attempt of the newer build is settled like any other")
		assert_true(m2:all_done())
		assert_eq(m2:level_to_play(), nil)
		assert_eq(m2:serialize().progress.beaten, 120, "not cut down to 100")
		local ok, why = m2:can_start(101, P)
		assert_false(ok)
		assert_eq(why, "all_done")
	end)
end)

describe("lives and levels", function()
	it("never costs a life on levels 1..20", function()
		local m = H.new()
		H.advance_to(m, 20)
		for _ = 1, 7 do H.lose(m, P) end
		assert_eq(m:lives(P).count, 5)
	end)

	it("lets levels 1..20 start with no lives", function()
		local m = H.new()
		H.advance_to(m, 15)
		m.s.lives.count, m.s.lives.next_at = 0, P + 1200
		assert_true(m:can_start(15, P))
		local r = m:start_level({ id = 15, difficulty = "easy" }, nil, P)
		assert_false(r.life_at_stake)
	end)

	it("takes a life for giving up or quitting after level 20", function()
		local m = H.new()
		H.advance_to(m, 21)
		local r = H.lose(m, P)
		assert_true(r.life_lost)
		assert_eq(r.reason, "out_of_moves")
		r = H.lose(m, P, true)
		assert_true(r.life_lost)
		assert_eq(r.reason, "quit")
		assert_eq(m:lives(P).count, 3)
	end)

	it("takes no life when the level is left before the first move", function()
		local m = H.new()
		H.advance_to(m, 21)
		m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		assert_true(m:cancel_level())
		assert_eq(m:lives(P).count, 5)
	end)

	it("does not start a level after 20 with no lives", function()
		local m = H.new()
		H.advance_to(m, 21)
		for _ = 1, 5 do H.lose(m, P) end
		local ok, why = m:can_start(21, P)
		assert_false(ok)
		assert_eq(why, "no_lives")
		ok, why = m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		assert_false(ok)
		assert_eq(why, "no_lives")
		assert_true(m:can_start(21, P + 1200), "a life came back")
	end)

	it("plays for free with infinite lives", function()
		local m = H.new()
		H.advance_to(m, 21)
		for _ = 1, 5 do H.lose(m, P) end
		m:grant({ infinite_minutes = 30 }, "test", P)
		assert_true(m:can_start(21, P))
		local r = m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		assert_false(r.life_at_stake)
		m:note_move()
		local l = m:finish_level({ won = false, level_id = 21 }, P + 60)
		assert_false(l.life_lost)
		assert_eq(m:lives(P + 60).count, 0)
	end)

	it("covers the whole attempt when infinite lives run out during it", function()
		local m = H.new()
		H.advance_to(m, 21)
		m:grant({ infinite_minutes = 15 }, "test", P)
		m:start_level({ id = 21, difficulty = "easy" }, nil, P)
		m:note_move()
		local l = m:finish_level({ won = false, level_id = 21 }, P + 3600)
		assert_false(l.life_lost)
		assert_eq(m:lives(P + 3600).count, 5)
	end)
end)

describe("win streak", function()
	it("counts only from level 12", function()
		local m = H.new()
		H.advance_to(m, 12)
		assert_eq(m:streak().count, 0)
		assert_false(m:streak().active and m:streak().count > 0)
		local r = H.win(m, T)
		assert_eq(r.streak, 1)
	end)

	it("gives riff, then sub, then disco, only unlocked ones", function()
		local m = H.new()
		H.advance_to(m, 12)
		assert_same(m:start_level({ id = 12, difficulty = "easy" }, nil, T).streak_boosters, {})
		m:finish_level({ won = true, level_id = 12, moves_at_win = 0 }, T)
		assert_same(m:streak_boosters_for_next_start(), { "riff" })
		assert_same(m:start_level({ id = 13, difficulty = "easy" }, nil, T).streak_boosters, { "riff" })
		m:finish_level({ won = true, level_id = 13, moves_at_win = 0 }, T)
		-- streak 2 at level 14: sub is still locked (unlocks at 16)
		assert_same(m:streak_boosters_for_next_start(), { "riff" })
		H.advance_to(m, 20)
		-- streak 8 at level 20: disco is still locked (unlocks at 22)
		local st = m:streak()
		assert_eq(st.count, 8)
		assert_true(st.active)
		assert_same(st.slots, {
			{ booster = "riff", wins = 1, lit = true, unlocked = true },
			{ booster = "sub", wins = 2, lit = true, unlocked = true },
			{ booster = "disco", wins = 3, lit = true, unlocked = false },
		})
		assert_same(st.boosters, { "riff", "sub" })
		H.advance_to(m, 22)
		assert_same(m:start_level({ id = 22, difficulty = "easy" }, nil, T).boosters, { "riff", "sub", "disco" })
	end)

	it("does not take streak boosters from the inventory", function()
		local m = H.new()
		H.advance_to(m, 14)
		local riff = m:booster_count("riff")
		m:start_level({ id = 14, difficulty = "easy" }, nil, T)
		assert_eq(m:booster_count("riff"), riff)
	end)

	it("resets on a loss and on quitting, but not on leaving before the first move", function()
		local m = H.new()
		H.advance_to(m, 16)
		assert_eq(m:streak().count, 4)
		m:start_level({ id = 16, difficulty = "easy" }, nil, T)
		m:cancel_level()
		assert_eq(m:streak().count, 4)
		local l = H.lose(m, T)
		assert_eq(l.streak_lost, 4)
		assert_eq(m:streak().count, 0)
		assert_same(m:streak_boosters_for_next_start(), {})
		H.win(m, T)
		H.win(m, T)
		l = H.lose(m, T, true)
		assert_eq(l.streak_lost, 2)
		assert_eq(m:streak().count, 0)
	end)
end)

describe("continues and ads", function()
	local m
	before_each(function()
		m = H.new()
		H.advance_to(m, 5)
		H.give(m, "coins", 10000)
		m:start_level({ id = 5, difficulty = "easy" }, nil, T)
	end)

	it("cost 700, 1400, 2100 with a riff from the second one", function()
		local coins = m:coins()
		assert_same(m:continue_offer(), { k = 1, price = 700, moves = 5, riff = false, affordable = true })
		assert_same(m:buy_continue(1), { k = 1, price = 700, moves = 5, riff = false })
		assert_same(m:buy_continue(2), { k = 2, price = 1400, moves = 5, riff = true })
		assert_same(m:buy_continue(3), { k = 3, price = 2100, moves = 5, riff = true })
		assert_eq(m:coins(), coins - 4200)
		assert_eq(m:continue_offer(), nil)
		local ok, why = m:buy_continue(4)
		assert_false(ok)
		assert_eq(why, "limit_reached")
		assert_eq(H.ledger_sum(m:drain_ledger(), "coins", "continue"), -4200)
	end)

	it("refuse a stale offer number", function()
		m:buy_continue(1)
		local coins = m:coins()
		local ok, why = m:buy_continue(1)
		assert_false(ok)
		assert_eq(why, "stale_offer")
		assert_eq(m:coins(), coins)
		assert_error(function() m:buy_continue() end, "offer number")
	end)

	it("reset for every attempt", function()
		m:buy_continue(1)
		m:buy_continue(2)
		m:finish_level({ won = false, level_id = 5 }, T)
		m:start_level({ id = 5, difficulty = "easy" }, nil, T)
		assert_eq(m:continue_offer().price, 700)
	end)

	it("fail cleanly without coins", function()
		H.give(m, "coins", -m:coins() + 1399)
		assert_true(m:buy_continue(1))
		assert_eq(m:coins(), 699)
		assert_false(m:continue_offer().affordable)
		local ok, why = m:buy_continue(2)
		assert_false(ok)
		assert_eq(why, "not_enough_coins")
		assert_eq(m:coins(), 699)
		assert_eq(m:continue_offer().k, 2, "the offer stays")
	end)

	it("give +3 moves for an ad once per attempt", function()
		assert_same(m:grant_ad_moves(), { moves = 3 })
		local ok, why = m:grant_ad_moves()
		assert_false(ok)
		assert_eq(why, "already_used")
		m:finish_level({ won = false, level_id = 5 }, T)
		ok, why = m:grant_ad_moves()
		assert_false(ok)
		assert_eq(why, "no_run")
		m:start_level({ id = 5, difficulty = "easy" }, nil, T)
		assert_same(m:grant_ad_moves(), { moves = 3 })
	end)

	it("need an attempt", function()
		m:cancel_level()
		assert_eq(m:continue_offer(), nil)
		local ok, why = m:buy_continue(1)
		assert_false(ok)
		assert_eq(why, "no_run")
	end)
end)

describe("attempt interrupted by an app kill", function()
	it("counts as a loss after the first move", function()
		local m = H.new()
		H.advance_to(m, 25)
		m:start_level({ id = 25, difficulty = "hard" }, nil, P)
		m:note_move()
		local m2, info = Meta.load(H.districts(), m:serialize(), nil, 1, P + 5)
		assert_eq(info.interrupted, "loss")
		assert_same(info.loss, { won = false, level_id = 25, reason = "interrupted", life_lost = true, streak_lost = 13, fails = 1 })
		assert_true(m2:dirty())
		assert_eq(m2:run(), nil)
		assert_eq(m2:lives(P + 5).count, 4)
		assert_eq(m2:streak().count, 0)
		assert_same(m2:attempts(25), { attempts = 1, fails = 1 })
		assert_eq(m2:level_to_play(), 25)
	end)

	it("is cancelled before the first move", function()
		local m = H.new()
		H.advance_to(m, 25)
		m:start_level({ id = 25, difficulty = "hard" }, { "riff" }, P)
		local riff = m:booster_count("riff")
		local m2, info = Meta.load(H.districts(), m:serialize(), nil, 1, P + 5)
		assert_eq(info.interrupted, "cancelled")
		assert_eq(info.loss, nil)
		assert_eq(m2:booster_count("riff"), riff + 1)
		assert_eq(m2:lives(P + 5).count, 5)
		assert_eq(m2:streak().count, 13, "wins on levels 12..24")
		assert_same(m2:attempts(25), { attempts = 0, fails = 0 })
	end)
end)
