#!/usr/bin/env python3
"""Generate the Defold resources that mirror the generated assets.

    python3 tools/gen_defold.py            # from anywhere; paths are repo-relative
    python3 tools/gen_defold.py --check    # exit 1 if any output would change

Reads whatever exists (manifests may be missing or partial; directories are
scanned as the source of truth, manifests only add metadata such as nine-slice):
  assets/images/**.png          + assets/images/manifest.json (optional)
  assets/sounds/{notes,sfx}/*.ogg
  assets/music/<district>/<stem>.ogg
  assets/fonts/*.ttf
  content/districts.json        (district ids: their atlases always exist)
  client/i18n.lua, content/districts.json   (extra glyphs the fonts must contain)

Writes (never edit these by hand, re-run the generator instead):
  assets/gen/*.atlas            game, ui, district_<id>, bg_<id>[_night], ...
  assets/gen/placeholder.png    8x8 white image present in every atlas ("white")
  assets/gen/fonts/*.font       title, button, number, body, small
  assets/gen/audio.go           audio game object: main/audio.script + one sound
                                component per note / sfx / music stem
  main/overlay.gui, screens/*/*.gui   minimal GUI scenes (script, fonts,
                                textures); their nodes are built in Lua
  client/assets_index.lua       registry of everything above for the scripts

Atlas grouping:
  game  = pieces + specials + blockers + board + fx
  ui    = ui (incl. ui/icons) + bit + logo
  district_<id> = districts/<id>/* except bg*.png
  bg_<id>, bg_<id>_<variant> = districts/<id>/bg.png, bg_<variant>.png (one texture each)
  bg_<name> = backgrounds/<name>.png, "bg_" prefix / "_bg" suffix dropped (one texture each)
  any other folder = an atlas named after the folder
Animation id of an image = its path under assets/images without ".png",
"/" replaced by "_" (pieces/red.png -> "pieces_red"). Output is sorted, so
re-running on the same inputs gives byte-identical files.
"""
import argparse
import json
import os
import re
import struct
import sys
import zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
IMAGES = "assets/images"
SOUNDS = "assets/sounds"
MUSIC = "assets/music"
FONTS = "assets/fonts"
GEN = "assets/gen"
INDEX = "client/assets_index.lua"
AUDIO_SCRIPT = "/main/audio.script"

GAME_GROUPS = ("pieces", "specials", "blockers", "board", "fx")
UI_GROUPS = ("ui", "bit", "logo", "icons")

HEADER_PB = "# Generated by tools/gen_defold.py - do not edit, re-run the generator.\n"

# Fonts: name -> (ttf, size, outline_width, shadow_alpha, shadow_blur, shadow_y)
FONT_SPECS = {
    "title": ("Rubik-Black.ttf", 72, 5.0, 0.35, 3, -5.0),
    "button": ("Rubik-Black.ttf", 44, 3.0, 0.30, 2, -3.0),
    "number": ("Rubik-Bold.ttf", 40, 3.0, 0.30, 2, -3.0),
    "body": ("Nunito-Bold.ttf", 32, 0.0, 0.0, 0, 0.0),
    "small": ("Nunito-Bold.ttf", 24, 0.0, 0.0, 0, 0.0),
}

# GUI scenes: path -> (script, texture groups). Groups: atlas names, or
# "districts" (every district_<id>), "district_bgs" (every bg_<id>*),
# "backgrounds" (every bg_<name> from assets/images/backgrounds).
GUI_SPECS = {
    "main/overlay.gui": ("/main/overlay.gui_script", ["ui"]),
    "screens/splash/splash.gui": ("/screens/splash/splash.gui_script", ["ui"]),
    "screens/town/town.gui": ("/screens/town/town.gui_script", ["ui", "districts", "district_bgs"]),
    "screens/level/level.gui": ("/screens/level/level.gui_script", ["game", "ui", "backgrounds"]),
}
GUI_MAX_NODES = 1024

BASE_CHARS = "".join(chr(c) for c in range(32, 127))
CYRILLIC = "".join(chr(c) for c in range(0x410, 0x450)) + "Ёё"
LATIN1 = "".join(chr(c) for c in range(0xC0, 0x100))  # é in "Café", ü, ñ, ...
EXTRA_CHARS = "«»—–…№•×−·°€₽©® ‘’“”„"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def rel(*parts):
    return os.path.join(ROOT, *parts)


def res_path(relpath):
    """Repo-relative path -> Defold resource path."""
    return "/" + relpath.replace(os.sep, "/")


def pb_string(s):
    """Protobuf text-format string literal (non-ASCII as octal UTF-8 bytes)."""
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "'":
            out.append("\\'")
        elif c == "\n":
            out.append("\\n")
        elif 32 <= b < 127:
            out.append(c)
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def png_size(path):
    with open(path, "rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    w, h = struct.unpack(">II", head[16:24])
    return w, h


def white_png(size=8):
    raw = b"".join(b"\x00" + b"\xff\xff\xff\xff" * size for _ in range(size))

    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")


def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def list_files(base, ext):
    """Sorted repo-relative paths of files with ext under base (recursive)."""
    out = []
    root = rel(base)
    if not os.path.isdir(root):
        return out
    for dp, dns, fns in os.walk(root):
        dns.sort()
        for fn in sorted(fns):
            if fn.lower().endswith(ext) and not fn.startswith("."):
                out.append(os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, "/"))
    return sorted(out)


def ident(s):
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


# ---------------------------------------------------------------------------
# images -> atlases
# ---------------------------------------------------------------------------
def district_ids():
    data = load_json(rel("content", "districts.json")) or {}
    return [d["id"] for d in data.get("districts", []) if isinstance(d, dict) and "id" in d]


def collect_images():
    """{image_key: {path, w, h, slice9?}} for every png under assets/images."""
    manifest = load_json(rel(IMAGES, "manifest.json")) or {}
    mfiles = manifest.get("files", {}) if isinstance(manifest, dict) else {}
    images = {}
    for p in list_files(IMAGES, ".png"):
        key = p[len(IMAGES) + 1:-4]
        size = png_size(rel(p))
        if not size:
            print("skip (not a png): " + p, file=sys.stderr)
            continue
        e = {"path": p, "w": size[0], "h": size[1]}
        m = mfiles.get(key + ".png")
        ns = m.get("nine_slice") if isinstance(m, dict) else None
        if isinstance(ns, (int, float)):
            e["slice9"] = [ns, ns, ns, ns]
        elif isinstance(ns, list) and len(ns) == 4 and all(isinstance(v, (int, float)) for v in ns):
            e["slice9"] = list(ns)  # left, top, right, bottom
        images[key] = e
    return images


def atlas_for(key):
    """Atlas name for an image key like 'pieces/red' or 'districts/cafe/bg'."""
    parts = key.split("/")
    top = parts[0]
    if len(parts) == 1:
        return "misc"
    if top in GAME_GROUPS:
        return "game"
    if top in UI_GROUPS:
        return "ui"
    if top == "districts" and len(parts) >= 3:
        did, name = parts[1], parts[-1]
        if name.startswith("bg"):
            return "bg_" + ident(did) + ident(name[2:])
        return "district_" + ident(did)
    if top == "backgrounds":
        name = "_".join(parts[1:])
        name = re.sub(r"^bg_|_bg$", "", name) or name
        return "bg_" + ident(name)
    return ident(top)


def plan_atlases(images, dids):
    atlases = {"game": [], "ui": []}
    for did in dids:  # always present so GUI scenes can reference them
        atlases["district_" + ident(did)] = []
        atlases["bg_" + ident(did)] = []
    for key in sorted(images):
        atlases.setdefault(atlas_for(key), []).append(key)
    return {k: sorted(v) for k, v in sorted(atlases.items())}


def anim_id(key):
    return key.replace("/", "_")


def atlas_text(keys, images):
    lines = [HEADER_PB.rstrip("\n")]
    entries = [("white", res_path(GEN + "/placeholder.png"))]
    entries += [(anim_id(k), res_path(images[k]["path"])) for k in keys]
    for aid, path in entries:
        lines += [
            "animations {",
            "  id: " + pb_string(aid),
            "  images {",
            "    image: " + pb_string(path),
            "  }",
            "  playback: PLAYBACK_NONE",
            "}",
        ]
    lines += ["margin: 2", "extrude_borders: 2", "inner_padding: 0"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# fonts
# ---------------------------------------------------------------------------
def content_chars():
    """Non-ASCII characters used by the UI strings and the content names."""
    chars = set()
    for p in (rel("client", "i18n.lua"), rel("content", "districts.json")):
        try:
            with open(p, encoding="utf-8") as f:
                chars |= {c for c in f.read() if ord(c) >= 0x80}
        except OSError:
            pass
    return "".join(sorted(chars))


def font_cmap(ttf):
    try:
        from fontTools.ttLib import TTFont  # optional: filters glyphs the font lacks
    except ImportError:
        return None
    try:
        return set(TTFont(ttf).getBestCmap().keys())
    except Exception:  # noqa: BLE001 - a broken font should not stop the generator
        return None


def font_text(name, spec, chars):
    ttf, size, outline, shadow_a, shadow_blur, shadow_y = spec
    lines = [
        HEADER_PB.rstrip("\n"),
        "font: " + pb_string(res_path(FONTS + "/" + ttf)),
        'material: "/builtins/fonts/font-df.material"',
        "size: %d" % size,
        "antialias: 1",
        "alpha: 1.0",
        "outline_alpha: %.1f" % (1.0 if outline > 0 else 0.0),
        "outline_width: %.1f" % outline,
        "shadow_alpha: %.2f" % shadow_a,
        "shadow_blur: %d" % shadow_blur,
        "shadow_x: 0.0",
        "shadow_y: %.1f" % shadow_y,
        "output_format: TYPE_DISTANCE_FIELD",
        "all_chars: false",
        "cache_width: 0",
        "cache_height: 0",
        "render_mode: %s" % ("MODE_MULTI_LAYER" if (outline > 0 or shadow_a > 0) else "MODE_SINGLE_LAYER"),
        "characters: " + pb_string(chars),
    ]
    return "\n".join(lines) + "\n"


def plan_fonts():
    wanted = BASE_CHARS + CYRILLIC + LATIN1 + EXTRA_CHARS + content_chars()
    out = {}
    for name, spec in sorted(FONT_SPECS.items()):
        ttf = rel(FONTS, spec[0])
        if not os.path.exists(ttf):
            print("font missing, skipped: " + spec[0], file=sys.stderr)
            continue
        cmap = font_cmap(ttf)
        chars = sorted(set(wanted))
        if cmap is not None:
            chars = [c for c in chars if ord(c) in cmap or c == " "]
        out[name] = (spec, "".join(chars))
    return out


# ---------------------------------------------------------------------------
# sounds -> audio game object
# ---------------------------------------------------------------------------
NOTE_RE = re.compile(r"^([a-z]+)_(\d+)$")


def plan_sounds():
    notes, sfx, music = {}, {}, {}
    comps = []  # (id, path, looping, group)
    for p in list_files(SOUNDS + "/notes", ".ogg"):
        name = os.path.basename(p)[:-4]
        m = NOTE_RE.match(name)
        if not m:
            continue
        cid = "note_" + ident(name)
        notes.setdefault(m.group(1), {})[int(m.group(2))] = cid
        comps.append((cid, p, 0, "sfx"))
    for p in list_files(SOUNDS + "/sfx", ".ogg"):
        name = os.path.basename(p)[:-4]
        cid = "sfx_" + ident(name)
        sfx[name] = cid
        comps.append((cid, p, 0, "sfx"))
    for p in list_files(MUSIC, ".ogg"):
        parts = p[len(MUSIC) + 1:-4].split("/")
        if len(parts) != 2:
            continue
        did, stem = parts
        cid = "music_" + ident(did) + "_" + ident(stem)
        music.setdefault(did, {})[stem] = cid
        comps.append((cid, p, 1, "music"))
    comps.sort()
    return {"notes": notes, "sfx": sfx, "music": music}, comps


def audio_go_text(comps):
    lines = [
        HEADER_PB.rstrip("\n"),
        "components {",
        '  id: "audio"',
        "  component: " + pb_string(AUDIO_SCRIPT),
        "}",
    ]
    for cid, path, looping, group in comps:
        data = ("sound: %s\nlooping: %d\ngroup: %s\ngain: 1.0\npan: 0.0\nspeed: 1.0\nloopcount: 0\n"
                % (pb_string(res_path(path)), looping, pb_string(group)))
        lines += [
            "embedded_components {",
            "  id: " + pb_string(cid),
            '  type: "sound"',
            "  data: " + pb_string(data),
            "}",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# GUI scenes
# ---------------------------------------------------------------------------
def gui_textures(groups, atlases):
    names = []
    for g in groups:
        if g == "districts":
            names += [a for a in atlases if a.startswith("district_")]
        elif g == "district_bgs":
            names += [a for a in atlases if a.startswith("bg_") and any(
                a == "bg_" + ident(d) or a.startswith("bg_" + ident(d) + "_") for d in district_ids())]
        elif g == "backgrounds":
            dbg = {a for a in atlases if a.startswith("bg_") and any(
                a == "bg_" + ident(d) or a.startswith("bg_" + ident(d) + "_") for d in district_ids())}
            names += [a for a in atlases if a.startswith("bg_") and a not in dbg]
        elif g in atlases:
            names.append(g)
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def gui_text(script, textures, fonts):
    lines = [HEADER_PB.rstrip("\n"), "script: " + pb_string(script)]
    for f in fonts:
        lines += ["fonts {", "  name: " + pb_string(f), "  font: " + pb_string(res_path(GEN + "/fonts/" + f + ".font")), "}"]
    for t in textures:
        lines += ["textures {", "  name: " + pb_string(t), "  texture: " + pb_string(res_path(GEN + "/" + t + ".atlas")), "}"]
    lines += [
        'material: "/builtins/materials/gui.material"',
        "adjust_reference: ADJUST_REFERENCE_DISABLED",
        "max_nodes: %d" % GUI_MAX_NODES,
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Lua registry
# ---------------------------------------------------------------------------
def index_text(images, atlases, fonts, sounds, guis):
    L = ["-- Generated by tools/gen_defold.py - do not edit, re-run the generator.",
         "-- Registry of the Defold resources built from assets/: scripts look",
         "-- things up here (usually through client/assets.lua) instead of",
         "-- hard-coding names, so a missing image or sound is a nil, not a crash.",
         "return {"]
    L.append("\tatlases = {")
    for name, keys in atlases.items():
        L.append("\t\t%s = { path = %s, anims = { %s } }," % (
            ident(name), lua_string(res_path(GEN + "/" + name + ".atlas")),
            ", ".join(lua_string(a) for a in ["white"] + [anim_id(k) for k in keys])))
    L.append("\t},")
    L.append("\timages = {")
    for key in sorted(images):
        e = images[key]
        extra = (", slice9 = { %s }" % ", ".join("%g" % v for v in e["slice9"])) if "slice9" in e else ""
        L.append("\t\t[%s] = { atlas = %s, anim = %s, w = %d, h = %d%s }," % (
            lua_string(key), lua_string(atlas_for(key)), lua_string(anim_id(key)), e["w"], e["h"], extra))
    L.append("\t},")
    L.append("\tfonts = {")
    for name in sorted(fonts):
        spec = fonts[name][0]
        L.append("\t\t%s = { path = %s, size = %d }," % (
            name, lua_string(res_path(GEN + "/fonts/" + name + ".font")), spec[1]))
    L.append("\t},")
    L.append("\tsounds = {")
    L.append("\t\tnotes = {")
    for color in sorted(sounds["notes"]):
        items = sounds["notes"][color]
        L.append("\t\t\t%s = { %s }," % (ident(color), ", ".join(
            "[%d] = %s" % (n, lua_string(items[n])) for n in sorted(items))))
    L.append("\t\t},")
    L.append("\t\tsfx = {")
    for name in sorted(sounds["sfx"]):
        L.append("\t\t\t[%s] = %s," % (lua_string(name), lua_string(sounds["sfx"][name])))
    L.append("\t\t},")
    L.append("\t\tmusic = {")
    for did in sorted(sounds["music"]):
        stems = sounds["music"][did]
        L.append("\t\t\t[%s] = { %s }," % (lua_string(did), ", ".join(
            "[%s] = %s" % (lua_string(s), lua_string(stems[s])) for s in sorted(stems))))
    L.append("\t\t},")
    L.append("\t},")
    L.append("\tguis = {")
    for path in sorted(guis):
        tex = guis[path]
        L.append("\t\t[%s] = { textures = { %s } }," % (lua_string(res_path(path)), ", ".join(lua_string(t) for t in tex)))
    L.append("\t},")
    L.append("}")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def build_outputs():
    outputs = {}  # repo-relative path -> bytes
    images = collect_images()
    dids = district_ids()
    atlases = plan_atlases(images, dids)
    outputs[GEN + "/placeholder.png"] = white_png()
    for name, keys in atlases.items():
        outputs[GEN + "/" + name + ".atlas"] = atlas_text(keys, images).encode("utf-8")
    fonts = plan_fonts()
    for name, (spec, chars) in fonts.items():
        outputs[GEN + "/fonts/" + name + ".font"] = font_text(name, spec, chars).encode("utf-8")
    sounds, comps = plan_sounds()
    outputs[GEN + "/audio.go"] = audio_go_text(comps).encode("utf-8")
    guis = {}
    for path, (script, groups) in sorted(GUI_SPECS.items()):
        tex = gui_textures(groups, atlases)
        guis[path] = tex
        outputs[path] = gui_text(script, tex, sorted(fonts)).encode("utf-8")
    outputs[INDEX] = index_text(images, atlases, fonts, sounds, guis).encode("utf-8")
    stats = {"images": len(images), "atlases": len(atlases), "fonts": len(fonts), "sounds": len(comps)}
    return outputs, stats


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are out of date")
    args = ap.parse_args()
    outputs, stats = build_outputs()
    changed = []
    for path, data in sorted(outputs.items()):
        full = rel(path)
        try:
            with open(full, "rb") as f:
                if f.read() == data:
                    continue
        except OSError:
            pass
        changed.append(path)
        if not args.check:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "wb") as f:
                f.write(data)
    # the generator owns assets/gen: remove outputs that are no longer produced
    stale = []
    gen_root = rel(GEN)
    if os.path.isdir(gen_root):
        for dp, _, fns in os.walk(gen_root):
            for fn in fns:
                p = os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, "/")
                if p not in outputs:
                    stale.append(p)
                    if not args.check:
                        os.remove(os.path.join(dp, fn))
    print("gen_defold: %(images)d images, %(atlases)d atlases, %(fonts)d fonts, %(sounds)d sound components" % stats)
    for p in changed:
        print(("out of date: " if args.check else "wrote ") + p)
    for p in sorted(stale):
        print(("stale: " if args.check else "removed ") + p)
    if args.check and (changed or stale):
        sys.exit(1)


if __name__ == "__main__":
    main()
