#!/usr/bin/env python3
"""Generate the Defold resources that mirror the generated assets.

    python3 tools/gen_defold.py            # from anywhere; paths are repo-relative
    python3 tools/gen_defold.py --check    # exit 1 if any output would change

Reads whatever exists (manifests may be missing or partial; directories are
scanned as the source of truth, manifests only add metadata):
  assets/images/**.png          + assets/images/manifest.json (optional: nine-slice;
                                built-in defaults cover the known panels/buttons)
  assets/sounds/{notes,sfx}/*.ogg + assets/sounds/manifest.json (optional: the
                                key of each effect, the mixer contract)
  assets/music/<district>/<stem>.ogg   (Ogg headers: every stem of a district
                                must have the same length -> error otherwise)
  assets/fonts/*.ttf            (a missing TTF falls back to another one, so
                                every font name always exists)
  content/districts.json        (district ids)
  client/i18n.lua, content/districts.json   (extra glyphs the fonts must contain)

Writes (never edit these by hand, re-run the generator instead):
  assets/gen/*.atlas            game, ui, bit, logo, ... (see grouping)
  assets/gen/placeholder.png    8x8 white image present in every atlas ("white")
  assets/gen/fonts/*.font       title, button, number, body, small
  assets/gen/audio.go           audio game object: main/audio.script + one sound
                                component per note (group "notes"), sfx (group
                                "sfx") and music stem (group "music")
  main/overlay.gui, screens/*/*.gui   minimal GUI scenes (script, fonts,
                                textures, materials); their nodes are built in Lua
  client/assets_index.lua       registry of everything above for the scripts

Atlas grouping:
  game  = pieces + specials + blockers + board + fx      (level)
  ui    = ui (incl. ui/icons)                            (every screen)
  meta  = a curated copy of the game images the meta screens show (goal
          icons, pre-level boosters, a few white fx sprites); only the town
          GUI loads it, so the town never holds the 8 MB game atlas. The
          registry marks these images with also = {"meta"}.
  any other folder = an atlas named after the folder
Loose images (not in any atlas): districts/**, backgrounds/**, bit/** (the
mascot) and logo/**. They ship as custom resources (game.project) and
screens load only the ones on display with image.load + gui.new_texture, so
the town holds one district's pictures instead of all of them, and a big
picture used on one screen does not keep a whole atlas page in memory.
Animation id of an image = its path under assets/images without ".png",
"/" replaced by "_" (pieces/red.png -> "pieces_red"); two images that map to
the same id get "_2", "_3", ... Output is sorted, so re-running on the same
inputs gives byte-identical files.
"""
import argparse
import fnmatch
import json
import os
import re
import struct
import sys
import zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
IMAGES = "assets/images"
SOUNDS = "assets/sounds"
MUSIC = "assets/music"
FONTS = "assets/fonts"
GEN = "assets/gen"
INDEX = "client/assets_index.lua"
AUDIO_SCRIPT = "/main/audio.script"

GAME_GROUPS = ("pieces", "specials", "blockers", "board", "fx")
UI_GROUPS = ("ui", "icons")
LOOSE_GROUPS = ("districts", "backgrounds", "bit", "logo")  # custom resources, loaded on demand
LOOSE_DIRS = tuple("/assets/images/" + g for g in LOOSE_GROUPS)
MIN_BG = (720, 1280)  # backgrounds below this look soft on 3x phones

# Nine-slice borders (left, top, right, bottom) when the images manifest has
# none: the panels and buttons stretch badly without them.
NINE_SLICE_DEFAULTS = [
    ("board/board_frame", [24, 24, 24, 24]),
    ("ui/button_*", [30, 30, 30, 40]),
    ("ui/moves_badge", [64, 64, 64, 64]),
    ("ui/panel", [40, 40, 40, 40]),
    ("ui/panel_*", [40, 40, 40, 40]),
    ("ui/ribbon", [112, 0, 112, 0]),
]

HEADER_PB = "# Generated by tools/gen_defold.py - do not edit, re-run the generator.\n"

# Fonts: name -> (ttf, size, outline_width, shadow_alpha, shadow_blur, shadow_y).
# A missing TTF is replaced by the first existing one of FONT_FALLBACK, then
# any TTF in assets/fonts, then the engine's builtin font (Latin only).
FONT_FALLBACK = ("Rubik-Black.ttf", "Rubik-Bold.ttf", "Nunito-Bold.ttf")
BUILTIN_FONT = "/builtins/fonts/vera_mo_bd.ttf"
FONT_SPECS = {
    "title": ("Rubik-Black.ttf", 72, 5.0, 0.35, 3, -5.0),
    "button": ("Rubik-Black.ttf", 44, 3.0, 0.30, 2, -3.0),
    "number": ("Rubik-Bold.ttf", 40, 3.0, 0.30, 2, -3.0),
    "body": ("Nunito-Bold.ttf", 32, 0.0, 0.0, 0, 0.0),
    "small": ("Nunito-Bold.ttf", 24, 0.0, 0.0, 0, 0.0),
}

# Images copied into the "meta" atlas (fnmatch patterns over image keys of the
# game atlas): what the start window, the shop, chests and the town effects
# draw. Missing files are simply left out.
META_ATLAS = (
    "pieces/*",
    "specials/riff", "specials/sub", "specials/disco",
    "blockers/record_box_1", "blockers/concrete_1", "blockers/noise", "blockers/balloon_red",
    "blockers/column_1", "blockers/floor_lit", "blockers/mic",
    "fx/spark", "fx/star_particle", "fx/confetti", "fx/glow_dot", "fx/ring", "fx/note",
)

# GUI scenes: path -> (script, atlases, materials[, max_nodes]). Only atlases
# that exist are referenced. District and background pictures are loose
# images (above). Materials: name -> material file (referenced only when the
# file exists). The town hosts the meta popups (gui/*.lua): more nodes.
GUI_SPECS = {
    "main/overlay.gui": ("/main/overlay.gui_script", ["ui"], []),
    "screens/splash/splash.gui": ("/screens/splash/splash.gui_script", ["ui"], []),
    "screens/town/town.gui": ("/screens/town/town.gui_script", ["ui", "meta"], ["grey"], 2048),
    "screens/level/level.gui": ("/screens/level/level.gui_script", ["game", "ui"], []),
}
MATERIALS = {"grey": "render/gui_grey.material"}
GUI_MAX_NODES = 1024

BASE_CHARS = "".join(chr(c) for c in range(32, 127))
CYRILLIC = "".join(chr(c) for c in range(0x410, 0x450)) + "Ёё"
LATIN1 = "".join(chr(c) for c in range(0xC0, 0x100))  # é in "Café", ü, ñ, ...
EXTRA_CHARS = "«»—–…№•×−·°€₽©® ‘’“”„"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def rel(*parts):
    return os.path.join(ROOT, *parts)


def res_path(relpath):
    """Repo-relative path -> Defold resource path."""
    return "/" + relpath.replace(os.sep, "/")


def pb_string(s):
    """Protobuf text-format string literal (non-ASCII as octal UTF-8 bytes)."""
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "'":
            out.append("\\'")
        elif c == "\n":
            out.append("\\n")
        elif 32 <= b < 127:
            out.append(c)
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def png_size(path):
    with open(path, "rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    w, h = struct.unpack(">II", head[16:24])
    return w, h


def white_png(size=8):
    raw = b"".join(b"\x00" + b"\xff\xff\xff\xff" * size for _ in range(size))

    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")


def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def list_files(base, ext):
    """Sorted repo-relative paths of files with ext under base (recursive)."""
    out = []
    root = rel(base)
    if not os.path.isdir(root):
        return out
    for dp, dns, fns in os.walk(root):
        dns.sort()
        for fn in sorted(fns):
            if fn.lower().endswith(ext) and not fn.startswith("."):
                out.append(os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, "/"))
    return sorted(out)


def ident(s):
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


# ---------------------------------------------------------------------------
# images -> atlases
# ---------------------------------------------------------------------------
def district_ids():
    data = load_json(rel("content", "districts.json")) or {}
    return [d["id"] for d in data.get("districts", []) if isinstance(d, dict) and "id" in d]


def default_slice9(key):
    for pattern, borders in NINE_SLICE_DEFAULTS:
        if fnmatch.fnmatchcase(key, pattern):
            return list(borders)
    return None


def valid_slice9(ns, w, h):
    """Borders fit the image: left + right < w and top + bottom < h."""
    return ns[0] + ns[2] < w and ns[1] + ns[3] < h


def collect_images(warnings):
    """{image_key: {path, w, h, slice9?}} for every png under assets/images."""
    manifest = load_json(rel(IMAGES, "manifest.json"))
    if not isinstance(manifest, dict):
        warnings.append("images manifest missing: built-in nine-slice defaults used")
        manifest = {}
    mfiles = manifest.get("files", {})
    if not isinstance(mfiles, dict):
        mfiles = {}
    images = {}
    for p in list_files(IMAGES, ".png"):
        key = p[len(IMAGES) + 1:-4]
        size = png_size(rel(p))
        if not size or size[0] <= 0 or size[1] <= 0:
            warnings.append("skip (not a png): " + p)
            continue
        e = {"path": p, "w": size[0], "h": size[1]}
        m = mfiles.get(key + ".png")
        ns = m.get("nine_slice") if isinstance(m, dict) else None
        from_manifest = True
        if isinstance(ns, (int, float)) and not isinstance(ns, bool):
            ns = [ns, ns, ns, ns]
        elif not (isinstance(ns, list) and len(ns) == 4 and all(isinstance(v, (int, float)) for v in ns)):
            ns, from_manifest = default_slice9(key), False
        if ns is not None:
            if valid_slice9(ns, size[0], size[1]):
                e["slice9"] = list(ns)  # left, top, right, bottom
            elif from_manifest:
                warnings.append("nine-slice %s does not fit %s (%dx%d): dropped" % (ns, key, size[0], size[1]))
        images[key] = e
    return images


def is_loose(key):
    return key.split("/")[0] in LOOSE_GROUPS and "/" in key


def atlas_for(key):
    """Atlas name for an image key like 'pieces/red', None for a loose image."""
    parts = key.split("/")
    top = parts[0]
    if len(parts) == 1:
        return "misc"
    if is_loose(key):
        return None
    if top in GAME_GROUPS:
        return "game"
    if top in UI_GROUPS:
        return "ui"
    return ident(top)


def meta_keys(images):
    """Image keys of the curated meta atlas (only images of the game atlas)."""
    return sorted(k for k in images if atlas_for(k) == "game"
                  and any(fnmatch.fnmatchcase(k, p) for p in META_ATLAS))


def plan_atlases(images):
    atlases = {"game": [], "ui": []}
    for key in sorted(images):
        a = atlas_for(key)
        if a is not None:
            atlases.setdefault(a, []).append(key)
    extra = meta_keys(images)
    if extra:
        atlases["meta"] = extra
    return {k: sorted(v) for k, v in sorted(atlases.items())}


def plan_anim_ids(atlases, warnings):
    """{image_key: anim id}, unique within each atlas ("white" is reserved).
    Copies in the meta atlas keep the id of their primary atlas."""
    out = {}
    for name, keys in atlases.items():
        if name == "meta":
            continue
        used = {"white"}
        for key in keys:
            base = key.replace("/", "_")
            aid, n = base, 1
            while aid in used:
                n += 1
                aid = "%s_%d" % (base, n)
            if aid != base:
                warnings.append("animation id clash in atlas %s: %s -> %s" % (name, key, aid))
            used.add(aid)
            out[key] = aid
    return out


def check_loose(images, dids, warnings):
    for key, e in sorted(images.items()):
        if not is_loose(key):
            continue
        parts = key.split("/")
        if parts[0] == "districts" and parts[1] not in dids:
            warnings.append("image of a district that is not in content/districts.json: " + key)
        name = parts[-1]
        if (parts[0] == "backgrounds" or name.startswith("bg")) and (e["w"] < MIN_BG[0] or e["h"] < MIN_BG[1]):
            warnings.append("low-res background %s (%dx%d): drawn at up to %.1fx on a 3x phone, ask for %dx%d" % (
                key, e["w"], e["h"], 1170 * 1280 / 720 / e["h"], MIN_BG[0], MIN_BG[1]))


def check_custom_resources(warnings):
    try:
        with open(rel("game.project"), encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return
    m = re.search(r"^custom_resources\s*=\s*(.*)$", text, re.M)
    have = {x.strip().rstrip("/") for x in (m.group(1).split(",") if m else [])}
    for d in LOOSE_DIRS:
        if d not in have:
            warnings.append("game.project custom_resources lacks %s: its loose images will not load" % d)


def atlas_text(keys, images, anims):
    lines = [HEADER_PB.rstrip("\n")]
    entries = [("white", res_path(GEN + "/placeholder.png"))]
    entries += [(anims[k], res_path(images[k]["path"])) for k in keys]
    for aid, path in entries:
        lines += [
            "animations {",
            "  id: " + pb_string(aid),
            "  images {",
            "    image: " + pb_string(path),
            "  }",
            "  playback: PLAYBACK_NONE",
            "}",
        ]
    lines += ["margin: 2", "extrude_borders: 2", "inner_padding: 0"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# fonts
# ---------------------------------------------------------------------------
def content_chars():
    """Non-ASCII characters used by the UI strings and the content names."""
    chars = set()
    for p in (rel("client", "i18n.lua"), rel("content", "districts.json")):
        try:
            with open(p, encoding="utf-8") as f:
                chars |= {c for c in f.read() if ord(c) >= 0x80}
        except OSError:
            pass
    return "".join(sorted(chars))


def font_cmap(ttf):
    try:
        from fontTools.ttLib import TTFont  # optional: filters glyphs the font lacks
    except ImportError:
        return None
    try:
        return set(TTFont(ttf).getBestCmap().keys())
    except Exception:  # noqa: BLE001 - a broken font should not stop the generator
        return None


def font_text(name, spec, chars, font_path):
    ttf, size, outline, shadow_a, shadow_blur, shadow_y = spec
    lines = [
        HEADER_PB.rstrip("\n"),
        "font: " + pb_string(font_path),
        'material: "/builtins/fonts/font-df.material"',
        "size: %d" % size,
        "antialias: 1",
        "alpha: 1.0",
        "outline_alpha: %.1f" % (1.0 if outline > 0 else 0.0),
        "outline_width: %.1f" % outline,
        "shadow_alpha: %.2f" % shadow_a,
        "shadow_blur: %d" % shadow_blur,
        "shadow_x: 0.0",
        "shadow_y: %.1f" % shadow_y,
        "output_format: TYPE_DISTANCE_FIELD",
        "all_chars: false",
        "cache_width: 0",
        "cache_height: 0",
        "render_mode: %s" % ("MODE_MULTI_LAYER" if (outline > 0 or shadow_a > 0) else "MODE_SINGLE_LAYER"),
        "characters: " + pb_string(chars),
    ]
    return "\n".join(lines) + "\n"


def resolve_ttf(ttf, warnings):
    """Resource path and local path of the TTF for a font spec, with fallbacks."""
    def usable(name):
        p = rel(FONTS, name)
        return os.path.isfile(p) and os.path.getsize(p) > 0
    if usable(ttf):
        return res_path(FONTS + "/" + ttf), rel(FONTS, ttf)
    others = [f for f in FONT_FALLBACK if usable(f)]
    others += [os.path.basename(p) for p in list_files(FONTS, ".ttf") if usable(os.path.basename(p))]
    if others:
        warnings.append("font %s missing: using %s" % (ttf, others[0]))
        return res_path(FONTS + "/" + others[0]), rel(FONTS, others[0])
    warnings.append("font %s missing and no TTF in %s: using the builtin font (no Cyrillic)" % (ttf, FONTS))
    return BUILTIN_FONT, None


def plan_fonts(warnings):
    """Every font name of FONT_SPECS, always (gui.set_font must never fail)."""
    wanted = BASE_CHARS + CYRILLIC + LATIN1 + EXTRA_CHARS + content_chars()
    out = {}
    for name, spec in sorted(FONT_SPECS.items()):
        font_path, local = resolve_ttf(spec[0], warnings)
        cmap = font_cmap(local) if local else None
        chars = sorted(set(wanted))
        if cmap is not None:
            chars = [c for c in chars if ord(c) in cmap or c == " "]
        out[name] = (spec, "".join(chars), font_path)
    return out


# ---------------------------------------------------------------------------
# sounds -> audio game object
# ---------------------------------------------------------------------------
NOTE_RE = re.compile(r"^([a-z]+)_(\d+)$")
STEM_TOLERANCE = 0.001  # seconds
# The parts of the manifest's mixer contract the engine reads.
MIXER_KEYS = ("notes_same_tick", "group_gain_db", "music_in_level_db", "music_big_combo_db")


def ogg_duration(path):
    """(seconds, sample_rate) of an Ogg Vorbis file from its headers, or None."""
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        return None
    i = data.find(b"OggS")
    if i < 0 or len(data) < i + 28:
        return None
    body = i + 27 + data[i + 26]
    packet = data[body:body + 16]
    if packet[:7] != b"\x01vorbis" or len(packet) < 16:
        return None
    rate = struct.unpack("<I", packet[12:16])[0]
    j = data.rfind(b"OggS")
    if rate <= 0 or j < 0 or len(data) < j + 14:
        return None
    granule = struct.unpack("<q", data[j + 6:j + 14])[0]
    if granule <= 0:
        return None
    return granule / rate, rate


def sounds_manifest(warnings):
    m = load_json(rel(SOUNDS, "manifest.json"))
    if not isinstance(m, dict):
        warnings.append("sounds manifest missing: no effect keys (tonal effects play in C), default mixer contract")
        return {}, {}
    keys = {}
    for e in m.get("sfx", []) if isinstance(m.get("sfx"), list) else []:
        if isinstance(e, dict) and isinstance(e.get("name"), str):
            k = e.get("key")
            if isinstance(k, str) and k:
                keys[e["name"]] = k
    src = m.get("mixer") if isinstance(m.get("mixer"), dict) else {}
    mixer = {k: src[k] for k in MIXER_KEYS if k in src}
    if isinstance(mixer.get("notes_same_tick"), dict):  # numbers only, not the prose
        mixer["notes_same_tick"] = {k: v for k, v in mixer["notes_same_tick"].items() if k != "rule"}
    return keys, mixer


def plan_sounds(warnings, errors):
    notes, sfx, music, loops = {}, {}, {}, {}
    comps = []  # (id, path, looping, group)
    for p in list_files(SOUNDS + "/notes", ".ogg"):
        name = os.path.basename(p)[:-4]
        m = NOTE_RE.match(name)
        if not m:
            continue
        if ogg_duration(rel(p)) is None:
            warnings.append("skip (not an Ogg Vorbis file): " + p)
            continue
        cid = "note_" + ident(name)
        notes.setdefault(m.group(1), {})[int(m.group(2))] = cid
        comps.append((cid, p, 0, "notes"))
    for p in list_files(SOUNDS + "/sfx", ".ogg"):
        name = os.path.basename(p)[:-4]
        if ogg_duration(rel(p)) is None:
            warnings.append("skip (not an Ogg Vorbis file): " + p)
            continue
        cid = "sfx_" + ident(name)
        sfx[name] = cid
        comps.append((cid, p, 0, "sfx"))
    lengths = {}
    for p in list_files(MUSIC, ".ogg"):
        parts = p[len(MUSIC) + 1:-4].split("/")
        if len(parts) != 2:
            continue
        did, stem = parts
        cid = "music_" + ident(did) + "_" + ident(stem)
        info = ogg_duration(rel(p))
        if info is None:
            warnings.append("skip (not an Ogg Vorbis file): " + p)
            continue
        music.setdefault(did, {})[stem] = cid
        lengths.setdefault(did, {})[stem] = info[0]
        comps.append((cid, p, 1, "music"))
    for did, stems in sorted(lengths.items()):
        lo, hi = min(stems.values()), max(stems.values())
        loops[did] = round(max(stems.values()), 6)
        if hi - lo > STEM_TOLERANCE:
            detail = ", ".join("%s %.4f s" % (k, v) for k, v in sorted(stems.items()))
            errors.append("stems of %s differ in length by %.1f ms (they would drift apart): %s" % (
                did, (hi - lo) * 1000, detail))
    comps.sort()
    sfx_keys, mixer = sounds_manifest(warnings)
    sfx_keys = {k: v for k, v in sfx_keys.items() if k in sfx}
    return {"notes": notes, "sfx": sfx, "music": music, "loops": loops, "sfx_keys": sfx_keys, "mixer": mixer}, comps


def audio_go_text(comps):
    lines = [
        HEADER_PB.rstrip("\n"),
        "components {",
        '  id: "audio"',
        "  component: " + pb_string(AUDIO_SCRIPT),
        "}",
    ]
    for cid, path, looping, group in comps:
        data = ("sound: %s\nlooping: %d\ngroup: %s\ngain: 1.0\npan: 0.0\nspeed: 1.0\nloopcount: 0\n"
                % (pb_string(res_path(path)), looping, pb_string(group)))
        lines += [
            "embedded_components {",
            "  id: " + pb_string(cid),
            '  type: "sound"',
            "  data: " + pb_string(data),
            "}",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# GUI scenes
# ---------------------------------------------------------------------------
def gui_textures(groups, atlases):
    return [g for g in groups if g in atlases]


def gui_materials(names):
    return [n for n in names if n in MATERIALS and os.path.isfile(rel(MATERIALS[n]))]


def gui_text(script, textures, fonts, materials, max_nodes=GUI_MAX_NODES):
    lines = [HEADER_PB.rstrip("\n"), "script: " + pb_string(script)]
    for f in fonts:
        lines += ["fonts {", "  name: " + pb_string(f), "  font: " + pb_string(res_path(GEN + "/fonts/" + f + ".font")), "}"]
    for t in textures:
        lines += ["textures {", "  name: " + pb_string(t), "  texture: " + pb_string(res_path(GEN + "/" + t + ".atlas")), "}"]
    for m in materials:
        lines += ["materials {", "  name: " + pb_string(m), "  material: " + pb_string(res_path(MATERIALS[m])), "}"]
    lines += [
        'material: "/builtins/materials/gui.material"',
        "adjust_reference: ADJUST_REFERENCE_DISABLED",
        "max_nodes: %d" % max_nodes,
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Lua registry
# ---------------------------------------------------------------------------
def lua_value(v, indent=""):
    """Plain JSON-like value -> Lua literal (sorted keys, deterministic)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return "%.10g" % v if isinstance(v, float) else "%d" % v
    if isinstance(v, str):
        return lua_string(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_value(x) for x in v) + " }" if v else "{}"
    if isinstance(v, dict):
        items = []
        for k in sorted(v):
            key = k if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k) else "[" + lua_string(k) + "]"
            items.append("%s = %s" % (key, lua_value(v[k])))
        return "{ " + ", ".join(items) + " }"
    return "nil"


def index_text(images, atlases, anims, fonts, sounds, guis):
    also = set(atlases.get("meta", []))
    L = ["-- Generated by tools/gen_defold.py - do not edit, re-run the generator.",
         "-- Registry of the Defold resources built from assets/: scripts look",
         "-- things up here (usually through client/assets.lua) instead of",
         "-- hard-coding names, so a missing image or sound is a nil, not a crash.",
         "return {"]
    L.append("\tatlases = {")
    for name, keys in atlases.items():
        L.append("\t\t%s = { path = %s, anims = { %s } }," % (
            ident(name), lua_string(res_path(GEN + "/" + name + ".atlas")),
            ", ".join(lua_string(a) for a in ["white"] + [anims[k] for k in keys])))
    L.append("\t},")
    L.append("\t-- atlas images {atlas, anim, w, h, slice9?, also? = {atlases holding a copy}};")
    L.append("\t-- loose images {file, w, h}")
    L.append("\timages = {")
    for key in sorted(images):
        e = images[key]
        extra = (", slice9 = { %s }" % ", ".join("%g" % v for v in e["slice9"])) if "slice9" in e else ""
        a = atlas_for(key)
        if a is None:
            L.append("\t\t[%s] = { file = %s, w = %d, h = %d%s }," % (
                lua_string(key), lua_string(res_path(e["path"])), e["w"], e["h"], extra))
        else:
            if key in also:
                extra += ', also = { "meta" }'
            L.append("\t\t[%s] = { atlas = %s, anim = %s, w = %d, h = %d%s }," % (
                lua_string(key), lua_string(a), lua_string(anims[key]), e["w"], e["h"], extra))
    L.append("\t},")
    L.append("\tfonts = {")
    for name in sorted(fonts):
        spec, _, font_path = fonts[name]
        L.append("\t\t%s = { path = %s, size = %d, ttf = %s }," % (
            name, lua_string(res_path(GEN + "/fonts/" + name + ".font")), spec[1], lua_string(font_path)))
    L.append("\t},")
    L.append("\tsounds = {")
    L.append("\t\tnotes = {")
    for color in sorted(sounds["notes"]):
        items = sounds["notes"][color]
        L.append("\t\t\t%s = { %s }," % (ident(color), ", ".join(
            "[%d] = %s" % (n, lua_string(items[n])) for n in sorted(items))))
    L.append("\t\t},")
    L.append("\t\tsfx = {")
    for name in sorted(sounds["sfx"]):
        L.append("\t\t\t[%s] = %s," % (lua_string(name), lua_string(sounds["sfx"][name])))
    L.append("\t\t},")
    L.append("\t\t-- key of each tonal effect (manifest): transposed to the district key like the notes")
    L.append("\t\tsfx_keys = %s," % lua_value(sounds["sfx_keys"]))
    L.append("\t\tmusic = {")
    for did in sorted(sounds["music"]):
        stems = sounds["music"][did]
        L.append("\t\t\t[%s] = { %s }," % (lua_string(did), ", ".join(
            "[%s] = %s" % (lua_string(s), lua_string(stems[s])) for s in sorted(stems))))
    L.append("\t\t},")
    L.append("\t\t-- loop length of each district track in seconds (from the Ogg headers)")
    L.append("\t\tloops = %s," % lua_value(sounds["loops"]))
    L.append("\t\t-- mixer contract of the audio agent (assets/sounds/manifest.json -> mixer)")
    L.append("\t\tmixer = %s," % lua_value(sounds["mixer"]))
    L.append("\t},")
    L.append("\tguis = {")
    for path in sorted(guis):
        tex, mats = guis[path]
        L.append("\t\t[%s] = { textures = %s, materials = %s }," % (
            lua_string(res_path(path)), lua_value(tex), lua_value(mats)))
    L.append("\t},")
    L.append("}")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def build_outputs(warnings, errors):
    outputs = {}  # repo-relative path -> bytes
    images = collect_images(warnings)
    dids = district_ids()
    check_loose(images, dids, warnings)
    check_custom_resources(warnings)
    atlases = plan_atlases(images)
    anims = plan_anim_ids(atlases, warnings)
    outputs[GEN + "/placeholder.png"] = white_png()
    for name, keys in atlases.items():
        outputs[GEN + "/" + name + ".atlas"] = atlas_text(keys, images, anims).encode("utf-8")
    fonts = plan_fonts(warnings)
    for name, (spec, chars, font_path) in fonts.items():
        outputs[GEN + "/fonts/" + name + ".font"] = font_text(name, spec, chars, font_path).encode("utf-8")
    sounds, comps = plan_sounds(warnings, errors)
    outputs[GEN + "/audio.go"] = audio_go_text(comps).encode("utf-8")
    guis = {}
    for path, spec in sorted(GUI_SPECS.items()):
        script, groups, mats = spec[:3]
        max_nodes = spec[3] if len(spec) > 3 else GUI_MAX_NODES
        tex = gui_textures(groups, atlases)
        mat = gui_materials(mats)
        guis[path] = (tex, mat)
        outputs[path] = gui_text(script, tex, sorted(fonts), mat, max_nodes).encode("utf-8")
    outputs[INDEX] = index_text(images, atlases, anims, fonts, sounds, guis).encode("utf-8")
    stats = {"images": len(images), "atlases": len(atlases), "fonts": len(fonts), "sounds": len(comps),
             "loose": sum(1 for k in images if is_loose(k))}
    return outputs, stats


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are out of date or assets are inconsistent")
    args = ap.parse_args()
    warnings, errors = [], []
    outputs, stats = build_outputs(warnings, errors)
    changed = []
    for path, data in sorted(outputs.items()):
        full = rel(path)
        try:
            with open(full, "rb") as f:
                if f.read() == data:
                    continue
        except OSError:
            pass
        changed.append(path)
        if not args.check:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "wb") as f:
                f.write(data)
    # the generator owns assets/gen: remove outputs that are no longer produced
    stale = []
    gen_root = rel(GEN)
    if os.path.isdir(gen_root):
        for dp, _, fns in os.walk(gen_root):
            for fn in fns:
                p = os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, "/")
                if p not in outputs:
                    stale.append(p)
                    if not args.check:
                        os.remove(os.path.join(dp, fn))
    print("gen_defold: %(images)d images (%(loose)d loose), %(atlases)d atlases, %(fonts)d fonts, "
          "%(sounds)d sound components" % stats)
    for w in warnings:
        print("warning: " + w, file=sys.stderr)
    for p in changed:
        print(("out of date: " if args.check else "wrote ") + p)
    for p in sorted(stale):
        print(("stale: " if args.check else "removed ") + p)
    allow = os.environ.get("GLOW_ALLOW_STEM_MISMATCH") == "1"
    for e in errors:
        print(("warning: " if allow else "ERROR: ") + e, file=sys.stderr)
    if errors and not allow:
        print("gen_defold: fix the assets (or set GLOW_ALLOW_STEM_MISMATCH=1 to build anyway)", file=sys.stderr)
        sys.exit(1)
    if args.check and (changed or stale):
        sys.exit(1)


if __name__ == "__main__":
    main()
